#!/usr/bin/python
#   tisdcc - Compiles C programs targetting TI z80 calculators
#   Copyright (C) 2009 Conrad Meyer <konrad@tylerc.org>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.



import optparse



import libtisdcc



parser = optparse.OptionParser(usage="Usage: %prog [options] file...", \
    version="%prog " + libtisdcc.VERSION)
parser.add_option("-o", None, dest="filename", help="output to FILE", \
    metavar="FILE")
(options, args) = parser.parse_args()
