#ifdef TI83P
unsigned char Bit_VertSplit();
unsigned char CheckSplitFlag();
void ClearRow(unsigned char a);
void ClrLCD();
void ClrLCDFull();
void ClrOP2S();
void ClrScrn();
void ClrScrnFull();
void ClrTxtShd();
void DispDone();
void DispHL(int n);
void DisplayImage(void *img, int loc);
void DispOP1A(unsigned char maxdigits);
void EraseEOL();
int FormBase();
int FormDCplx();
int FormEReal(unsigned char maxwidth);
int FormReal(unsigned char maxwidth);
void LoadPattern(unsigned char charequate);
void *Load_SFont(unsigned int offset);
void NewLine();
void OutputExpr(unsigned char col, unsigned char row);
void PutC(char c);
void PutMap(char c);
void PutPS(char *str);
void PutPSB(char *str);
void PutS(char *str);
void PutTokString(int tok);
void RestoreDisp(void *data, unsigned char numrows);
void RunIndicOff();
void RunIndicOn();
void SaveDisp(void *ptr);
void SetNorm_Vals();
unsigned char SFont_Len(unsigned int offset);
unsigned int SStringLength(char *str);
void VPutMap(char c);
void VPutS(char *str);
void VPutSN(char *str, unsigned char len);
void CloseEditBuf();
void CloseEditBufNoR();
void CloseEditEqu();
void CursorOff();
void CursorOn();
void DispEOL();
unsigned char IsEditEmpty();
char *KeyToString(int key);
void ReleaseBuffer();
void ErrArgument();
void ErrBadGuess();
void ErrBreak();
void ErrD_OP1_0();
void ErrD_OP1_LE_0();
void ErrD_OP1Not_R();
void ErrD_OP1NotPos();
void ErrD_OP1NotPosInt();
void ErrDataType();
void ErrDimension();
void ErrDimMismatch();
void ErrDivBy0();
void ErrDomain();
void ErrIncrement();
void ErrInvalid();
void ErrIterations();
void ErrLinkXmit();
void ErrMemory();
void ErrNon_Real();
void ErrNonReal(unsigned char numargs);
void ErrNotEnoughMem(unsigned int size);
void ErrOverflow();
void ErrSignChange();
void ErrSingularMat();
void ErrStat();
void ErrStatPlot();
void ErrSyntax();
void ErrTolTooSmall();
void ErrUndefined();
void JError(unsigned char flags);
void JErrorNo();
#endif
